### ISSUE TITLE
Implement Fio API calls to add transactions to be authorized later in IB

### ISSUE THREAD

**Issue by mark-stopka** [PERLUR/php-fio-api#2]
Fio API has an interface to import transactions via API, please see section 
6 IMPORT (UPLOAD) PLATEBNÍCH PŘÍKAZŮ DO BANK of the [Fio API manual](http://www.fio.cz/docs/cz/API_Bankovnictvi.pdf).

Please implement this functionality. Start with domestic transactions, SEPA payments and international transfers will be implemented later.

**Comment by mark-stopka** [comment]
Hello Petr, is there any update on this issue?

**Comment by kramapet** [comment]
Hi, 
just pushed update in issue-2-import where this enhancement is implemented.

**Comment by mark-stopka** [comment]
I have merged issue-2-import branch into master since it passes all tests. Please see #4 PR: Import domestic transactions using Fio API for more details.
